// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeElasticGPUClasses implements ElasticGPUClassInterface
type FakeElasticGPUClasses struct {
	Fake *FakeElasticgpuV1alpha1
}

var elasticgpuclassesResource = schema.GroupVersionResource{Group: "elasticgpu.io", Version: "v1alpha1", Resource: "elasticgpuclasses"}

var elasticgpuclassesKind = schema.GroupVersionKind{Group: "elasticgpu.io", Version: "v1alpha1", Kind: "ElasticGPUClass"}

// Get takes name of the elasticGPUClass, and returns the corresponding elasticGPUClass object, and an error if there is any.
func (c *FakeElasticGPUClasses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ElasticGPUClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(elasticgpuclassesResource, name), &v1alpha1.ElasticGPUClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClass), err
}

// List takes label and field selectors, and returns the list of ElasticGPUClasses that match those selectors.
func (c *FakeElasticGPUClasses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ElasticGPUClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(elasticgpuclassesResource, elasticgpuclassesKind, opts), &v1alpha1.ElasticGPUClassList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ElasticGPUClassList{ListMeta: obj.(*v1alpha1.ElasticGPUClassList).ListMeta}
	for _, item := range obj.(*v1alpha1.ElasticGPUClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested elasticGPUClasses.
func (c *FakeElasticGPUClasses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(elasticgpuclassesResource, opts))
}

// Create takes the representation of a elasticGPUClass and creates it.  Returns the server's representation of the elasticGPUClass, and an error, if there is any.
func (c *FakeElasticGPUClasses) Create(ctx context.Context, elasticGPUClass *v1alpha1.ElasticGPUClass, opts v1.CreateOptions) (result *v1alpha1.ElasticGPUClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(elasticgpuclassesResource, elasticGPUClass), &v1alpha1.ElasticGPUClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClass), err
}

// Update takes the representation of a elasticGPUClass and updates it. Returns the server's representation of the elasticGPUClass, and an error, if there is any.
func (c *FakeElasticGPUClasses) Update(ctx context.Context, elasticGPUClass *v1alpha1.ElasticGPUClass, opts v1.UpdateOptions) (result *v1alpha1.ElasticGPUClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(elasticgpuclassesResource, elasticGPUClass), &v1alpha1.ElasticGPUClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClass), err
}

// Delete takes name of the elasticGPUClass and deletes it. Returns an error if one occurs.
func (c *FakeElasticGPUClasses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(elasticgpuclassesResource, name, opts), &v1alpha1.ElasticGPUClass{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeElasticGPUClasses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(elasticgpuclassesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ElasticGPUClassList{})
	return err
}

// Patch applies the patch and returns the patched elasticGPUClass.
func (c *FakeElasticGPUClasses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticGPUClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(elasticgpuclassesResource, name, pt, data, subresources...), &v1alpha1.ElasticGPUClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClass), err
}
