// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGPUs implements GPUInterface
type FakeGPUs struct {
	Fake *FakeElasticgpuV1alpha1
}

var gpusResource = schema.GroupVersionResource{Group: "elasticgpu.io", Version: "v1alpha1", Resource: "gpus"}

var gpusKind = schema.GroupVersionKind{Group: "elasticgpu.io", Version: "v1alpha1", Kind: "GPU"}

// Get takes name of the gPU, and returns the corresponding gPU object, and an error if there is any.
func (c *FakeGPUs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPU, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(gpusResource, name), &v1alpha1.GPU{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPU), err
}

// List takes label and field selectors, and returns the list of GPUs that match those selectors.
func (c *FakeGPUs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPUList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(gpusResource, gpusKind, opts), &v1alpha1.GPUList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GPUList{ListMeta: obj.(*v1alpha1.GPUList).ListMeta}
	for _, item := range obj.(*v1alpha1.GPUList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gPUs.
func (c *FakeGPUs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(gpusResource, opts))
}

// Create takes the representation of a gPU and creates it.  Returns the server's representation of the gPU, and an error, if there is any.
func (c *FakeGPUs) Create(ctx context.Context, gPU *v1alpha1.GPU, opts v1.CreateOptions) (result *v1alpha1.GPU, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(gpusResource, gPU), &v1alpha1.GPU{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPU), err
}

// Update takes the representation of a gPU and updates it. Returns the server's representation of the gPU, and an error, if there is any.
func (c *FakeGPUs) Update(ctx context.Context, gPU *v1alpha1.GPU, opts v1.UpdateOptions) (result *v1alpha1.GPU, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(gpusResource, gPU), &v1alpha1.GPU{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPU), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGPUs) UpdateStatus(ctx context.Context, gPU *v1alpha1.GPU, opts v1.UpdateOptions) (*v1alpha1.GPU, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(gpusResource, "status", gPU), &v1alpha1.GPU{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPU), err
}

// Delete takes name of the gPU and deletes it. Returns an error if one occurs.
func (c *FakeGPUs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(gpusResource, name, opts), &v1alpha1.GPU{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGPUs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(gpusResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GPUList{})
	return err
}

// Patch applies the patch and returns the patched gPU.
func (c *FakeGPUs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPU, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(gpusResource, name, pt, data, subresources...), &v1alpha1.GPU{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPU), err
}
