// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeElasticGPUClaims implements ElasticGPUClaimInterface
type FakeElasticGPUClaims struct {
	Fake *FakeElasticgpuV1alpha1
	ns   string
}

var elasticgpuclaimsResource = schema.GroupVersionResource{Group: "elasticgpu.io", Version: "v1alpha1", Resource: "elasticgpuclaims"}

var elasticgpuclaimsKind = schema.GroupVersionKind{Group: "elasticgpu.io", Version: "v1alpha1", Kind: "ElasticGPUClaim"}

// Get takes name of the elasticGPUClaim, and returns the corresponding elasticGPUClaim object, and an error if there is any.
func (c *FakeElasticGPUClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ElasticGPUClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(elasticgpuclaimsResource, c.ns, name), &v1alpha1.ElasticGPUClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClaim), err
}

// List takes label and field selectors, and returns the list of ElasticGPUClaims that match those selectors.
func (c *FakeElasticGPUClaims) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ElasticGPUClaimList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(elasticgpuclaimsResource, elasticgpuclaimsKind, c.ns, opts), &v1alpha1.ElasticGPUClaimList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ElasticGPUClaimList{ListMeta: obj.(*v1alpha1.ElasticGPUClaimList).ListMeta}
	for _, item := range obj.(*v1alpha1.ElasticGPUClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested elasticGPUClaims.
func (c *FakeElasticGPUClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(elasticgpuclaimsResource, c.ns, opts))

}

// Create takes the representation of a elasticGPUClaim and creates it.  Returns the server's representation of the elasticGPUClaim, and an error, if there is any.
func (c *FakeElasticGPUClaims) Create(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.CreateOptions) (result *v1alpha1.ElasticGPUClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(elasticgpuclaimsResource, c.ns, elasticGPUClaim), &v1alpha1.ElasticGPUClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClaim), err
}

// Update takes the representation of a elasticGPUClaim and updates it. Returns the server's representation of the elasticGPUClaim, and an error, if there is any.
func (c *FakeElasticGPUClaims) Update(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.UpdateOptions) (result *v1alpha1.ElasticGPUClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(elasticgpuclaimsResource, c.ns, elasticGPUClaim), &v1alpha1.ElasticGPUClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClaim), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeElasticGPUClaims) UpdateStatus(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.UpdateOptions) (*v1alpha1.ElasticGPUClaim, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(elasticgpuclaimsResource, "status", c.ns, elasticGPUClaim), &v1alpha1.ElasticGPUClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClaim), err
}

// Delete takes name of the elasticGPUClaim and deletes it. Returns an error if one occurs.
func (c *FakeElasticGPUClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(elasticgpuclaimsResource, c.ns, name, opts), &v1alpha1.ElasticGPUClaim{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeElasticGPUClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(elasticgpuclaimsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ElasticGPUClaimList{})
	return err
}

// Patch applies the patch and returns the patched elasticGPUClaim.
func (c *FakeElasticGPUClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticGPUClaim, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(elasticgpuclaimsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ElasticGPUClaim{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticGPUClaim), err
}
