// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "elasticgpu.io/elastic-gpu/client/clientset/versioned/typed/elasticgpu/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeElasticgpuV1alpha1 struct {
	*testing.Fake
}

func (c *FakeElasticgpuV1alpha1) ElasticGPUs() v1alpha1.ElasticGPUInterface {
	return &FakeElasticGPUs{c}
}

func (c *FakeElasticgpuV1alpha1) ElasticGPUClaims(namespace string) v1alpha1.ElasticGPUClaimInterface {
	return &FakeElasticGPUClaims{c, namespace}
}

func (c *FakeElasticgpuV1alpha1) ElasticGPUClasses() v1alpha1.ElasticGPUClassInterface {
	return &FakeElasticGPUClasses{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeElasticgpuV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
