// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	elasticgpuv1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	versioned "elasticgpu.io/elastic-gpu/client/clientset/versioned"
	internalinterfaces "elasticgpu.io/elastic-gpu/client/informers/externalversions/internalinterfaces"
	v1alpha1 "elasticgpu.io/elastic-gpu/client/listers/elasticgpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ElasticGPUClassInformer provides access to a shared informer and lister for
// ElasticGPUClasses.
type ElasticGPUClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ElasticGPUClassLister
}

type elasticGPUClassInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewElasticGPUClassInformer constructs a new informer for ElasticGPUClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewElasticGPUClassInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredElasticGPUClassInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredElasticGPUClassInformer constructs a new informer for ElasticGPUClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredElasticGPUClassInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticgpuV1alpha1().ElasticGPUClasses().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticgpuV1alpha1().ElasticGPUClasses().Watch(context.TODO(), options)
			},
		},
		&elasticgpuv1alpha1.ElasticGPUClass{},
		resyncPeriod,
		indexers,
	)
}

func (f *elasticGPUClassInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredElasticGPUClassInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *elasticGPUClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&elasticgpuv1alpha1.ElasticGPUClass{}, f.defaultInformer)
}

func (f *elasticGPUClassInformer) Lister() v1alpha1.ElasticGPUClassLister {
	return v1alpha1.NewElasticGPUClassLister(f.Informer().GetIndexer())
}
