// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	elasticgpuv1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	versioned "elasticgpu.io/elastic-gpu/client/clientset/versioned"
	internalinterfaces "elasticgpu.io/elastic-gpu/client/informers/externalversions/internalinterfaces"
	v1alpha1 "elasticgpu.io/elastic-gpu/client/listers/elasticgpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ElasticGPUClaimInformer provides access to a shared informer and lister for
// ElasticGPUClaims.
type ElasticGPUClaimInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ElasticGPUClaimLister
}

type elasticGPUClaimInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewElasticGPUClaimInformer constructs a new informer for ElasticGPUClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewElasticGPUClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredElasticGPUClaimInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredElasticGPUClaimInformer constructs a new informer for ElasticGPUClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredElasticGPUClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticgpuV1alpha1().ElasticGPUClaims(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticgpuV1alpha1().ElasticGPUClaims(namespace).Watch(context.TODO(), options)
			},
		},
		&elasticgpuv1alpha1.ElasticGPUClaim{},
		resyncPeriod,
		indexers,
	)
}

func (f *elasticGPUClaimInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredElasticGPUClaimInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *elasticGPUClaimInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&elasticgpuv1alpha1.ElasticGPUClaim{}, f.defaultInformer)
}

func (f *elasticGPUClaimInformer) Lister() v1alpha1.ElasticGPUClaimLister {
	return v1alpha1.NewElasticGPUClaimLister(f.Informer().GetIndexer())
}
