// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	elasticgpuv1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	versioned "elasticgpu.io/elastic-gpu/client/clientset/versioned"
	internalinterfaces "elasticgpu.io/elastic-gpu/client/informers/externalversions/internalinterfaces"
	v1alpha1 "elasticgpu.io/elastic-gpu/client/listers/elasticgpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GPUInformer provides access to a shared informer and lister for
// GPUs.
type GPUInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GPULister
}

type gPUInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewGPUInformer constructs a new informer for GPU type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGPUInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGPUInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredGPUInformer constructs a new informer for GPU type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGPUInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticgpuV1alpha1().GPUs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticgpuV1alpha1().GPUs().Watch(context.TODO(), options)
			},
		},
		&elasticgpuv1alpha1.GPU{},
		resyncPeriod,
		indexers,
	)
}

func (f *gPUInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGPUInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gPUInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&elasticgpuv1alpha1.GPU{}, f.defaultInformer)
}

func (f *gPUInformer) Lister() v1alpha1.GPULister {
	return v1alpha1.NewGPULister(f.Informer().GetIndexer())
}
