// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ElasticGPUClaimLister helps list ElasticGPUClaims.
// All objects returned here must be treated as read-only.
type ElasticGPUClaimLister interface {
	// List lists all ElasticGPUClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ElasticGPUClaim, err error)
	// ElasticGPUClaims returns an object that can list and get ElasticGPUClaims.
	ElasticGPUClaims(namespace string) ElasticGPUClaimNamespaceLister
	ElasticGPUClaimListerExpansion
}

// elasticGPUClaimLister implements the ElasticGPUClaimLister interface.
type elasticGPUClaimLister struct {
	indexer cache.Indexer
}

// NewElasticGPUClaimLister returns a new ElasticGPUClaimLister.
func NewElasticGPUClaimLister(indexer cache.Indexer) ElasticGPUClaimLister {
	return &elasticGPUClaimLister{indexer: indexer}
}

// List lists all ElasticGPUClaims in the indexer.
func (s *elasticGPUClaimLister) List(selector labels.Selector) (ret []*v1alpha1.ElasticGPUClaim, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ElasticGPUClaim))
	})
	return ret, err
}

// ElasticGPUClaims returns an object that can list and get ElasticGPUClaims.
func (s *elasticGPUClaimLister) ElasticGPUClaims(namespace string) ElasticGPUClaimNamespaceLister {
	return elasticGPUClaimNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ElasticGPUClaimNamespaceLister helps list and get ElasticGPUClaims.
// All objects returned here must be treated as read-only.
type ElasticGPUClaimNamespaceLister interface {
	// List lists all ElasticGPUClaims in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ElasticGPUClaim, err error)
	// Get retrieves the ElasticGPUClaim from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ElasticGPUClaim, error)
	ElasticGPUClaimNamespaceListerExpansion
}

// elasticGPUClaimNamespaceLister implements the ElasticGPUClaimNamespaceLister
// interface.
type elasticGPUClaimNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ElasticGPUClaims in the indexer for a given namespace.
func (s elasticGPUClaimNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ElasticGPUClaim, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ElasticGPUClaim))
	})
	return ret, err
}

// Get retrieves the ElasticGPUClaim from the indexer for a given namespace and name.
func (s elasticGPUClaimNamespaceLister) Get(name string) (*v1alpha1.ElasticGPUClaim, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("elasticgpuclaim"), name)
	}
	return obj.(*v1alpha1.ElasticGPUClaim), nil
}
