// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ElasticGPUListerExpansion allows custom methods to be added to
// ElasticGPULister.
type ElasticGPUListerExpansion interface{}

// ElasticGPUClaimListerExpansion allows custom methods to be added to
// ElasticGPUClaimLister.
type ElasticGPUClaimListerExpansion interface{}

// ElasticGPUClaimNamespaceListerExpansion allows custom methods to be added to
// ElasticGPUClaimNamespaceLister.
type ElasticGPUClaimNamespaceListerExpansion interface{}

// ElasticGPUClassListerExpansion allows custom methods to be added to
// ElasticGPUClassLister.
type ElasticGPUClassListerExpansion interface{}
