// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	scheme "elasticgpu.io/elastic-gpu/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ElasticGPUClassesGetter has a method to return a ElasticGPUClassInterface.
// A group's client should implement this interface.
type ElasticGPUClassesGetter interface {
	ElasticGPUClasses() ElasticGPUClassInterface
}

// ElasticGPUClassInterface has methods to work with ElasticGPUClass resources.
type ElasticGPUClassInterface interface {
	Create(ctx context.Context, elasticGPUClass *v1alpha1.ElasticGPUClass, opts v1.CreateOptions) (*v1alpha1.ElasticGPUClass, error)
	Update(ctx context.Context, elasticGPUClass *v1alpha1.ElasticGPUClass, opts v1.UpdateOptions) (*v1alpha1.ElasticGPUClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ElasticGPUClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ElasticGPUClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticGPUClass, err error)
	ElasticGPUClassExpansion
}

// elasticGPUClasses implements ElasticGPUClassInterface
type elasticGPUClasses struct {
	client rest.Interface
}

// newElasticGPUClasses returns a ElasticGPUClasses
func newElasticGPUClasses(c *ElasticgpuV1alpha1Client) *elasticGPUClasses {
	return &elasticGPUClasses{
		client: c.RESTClient(),
	}
}

// Get takes name of the elasticGPUClass, and returns the corresponding elasticGPUClass object, and an error if there is any.
func (c *elasticGPUClasses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ElasticGPUClass, err error) {
	result = &v1alpha1.ElasticGPUClass{}
	err = c.client.Get().
		Resource("elasticgpuclasses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ElasticGPUClasses that match those selectors.
func (c *elasticGPUClasses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ElasticGPUClassList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ElasticGPUClassList{}
	err = c.client.Get().
		Resource("elasticgpuclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested elasticGPUClasses.
func (c *elasticGPUClasses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("elasticgpuclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a elasticGPUClass and creates it.  Returns the server's representation of the elasticGPUClass, and an error, if there is any.
func (c *elasticGPUClasses) Create(ctx context.Context, elasticGPUClass *v1alpha1.ElasticGPUClass, opts v1.CreateOptions) (result *v1alpha1.ElasticGPUClass, err error) {
	result = &v1alpha1.ElasticGPUClass{}
	err = c.client.Post().
		Resource("elasticgpuclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(elasticGPUClass).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a elasticGPUClass and updates it. Returns the server's representation of the elasticGPUClass, and an error, if there is any.
func (c *elasticGPUClasses) Update(ctx context.Context, elasticGPUClass *v1alpha1.ElasticGPUClass, opts v1.UpdateOptions) (result *v1alpha1.ElasticGPUClass, err error) {
	result = &v1alpha1.ElasticGPUClass{}
	err = c.client.Put().
		Resource("elasticgpuclasses").
		Name(elasticGPUClass.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(elasticGPUClass).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the elasticGPUClass and deletes it. Returns an error if one occurs.
func (c *elasticGPUClasses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("elasticgpuclasses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *elasticGPUClasses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("elasticgpuclasses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched elasticGPUClass.
func (c *elasticGPUClasses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticGPUClass, err error) {
	result = &v1alpha1.ElasticGPUClass{}
	err = c.client.Patch(pt).
		Resource("elasticgpuclasses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
