// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	scheme "elasticgpu.io/elastic-gpu/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ElasticGPUClaimsGetter has a method to return a ElasticGPUClaimInterface.
// A group's client should implement this interface.
type ElasticGPUClaimsGetter interface {
	ElasticGPUClaims(namespace string) ElasticGPUClaimInterface
}

// ElasticGPUClaimInterface has methods to work with ElasticGPUClaim resources.
type ElasticGPUClaimInterface interface {
	Create(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.CreateOptions) (*v1alpha1.ElasticGPUClaim, error)
	Update(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.UpdateOptions) (*v1alpha1.ElasticGPUClaim, error)
	UpdateStatus(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.UpdateOptions) (*v1alpha1.ElasticGPUClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ElasticGPUClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ElasticGPUClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticGPUClaim, err error)
	ElasticGPUClaimExpansion
}

// elasticGPUClaims implements ElasticGPUClaimInterface
type elasticGPUClaims struct {
	client rest.Interface
	ns     string
}

// newElasticGPUClaims returns a ElasticGPUClaims
func newElasticGPUClaims(c *ElasticgpuV1alpha1Client, namespace string) *elasticGPUClaims {
	return &elasticGPUClaims{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the elasticGPUClaim, and returns the corresponding elasticGPUClaim object, and an error if there is any.
func (c *elasticGPUClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ElasticGPUClaim, err error) {
	result = &v1alpha1.ElasticGPUClaim{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ElasticGPUClaims that match those selectors.
func (c *elasticGPUClaims) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ElasticGPUClaimList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ElasticGPUClaimList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested elasticGPUClaims.
func (c *elasticGPUClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a elasticGPUClaim and creates it.  Returns the server's representation of the elasticGPUClaim, and an error, if there is any.
func (c *elasticGPUClaims) Create(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.CreateOptions) (result *v1alpha1.ElasticGPUClaim, err error) {
	result = &v1alpha1.ElasticGPUClaim{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(elasticGPUClaim).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a elasticGPUClaim and updates it. Returns the server's representation of the elasticGPUClaim, and an error, if there is any.
func (c *elasticGPUClaims) Update(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.UpdateOptions) (result *v1alpha1.ElasticGPUClaim, err error) {
	result = &v1alpha1.ElasticGPUClaim{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		Name(elasticGPUClaim.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(elasticGPUClaim).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *elasticGPUClaims) UpdateStatus(ctx context.Context, elasticGPUClaim *v1alpha1.ElasticGPUClaim, opts v1.UpdateOptions) (result *v1alpha1.ElasticGPUClaim, err error) {
	result = &v1alpha1.ElasticGPUClaim{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		Name(elasticGPUClaim.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(elasticGPUClaim).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the elasticGPUClaim and deletes it. Returns an error if one occurs.
func (c *elasticGPUClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *elasticGPUClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched elasticGPUClaim.
func (c *elasticGPUClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticGPUClaim, err error) {
	result = &v1alpha1.ElasticGPUClaim{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("elasticgpuclaims").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
