// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "elasticgpu.io/elastic-gpu/apis/elasticgpu/v1alpha1"
	scheme "elasticgpu.io/elastic-gpu/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GPUsGetter has a method to return a GPUInterface.
// A group's client should implement this interface.
type GPUsGetter interface {
	GPUs() GPUInterface
}

// GPUInterface has methods to work with GPU resources.
type GPUInterface interface {
	Create(ctx context.Context, gPU *v1alpha1.GPU, opts v1.CreateOptions) (*v1alpha1.GPU, error)
	Update(ctx context.Context, gPU *v1alpha1.GPU, opts v1.UpdateOptions) (*v1alpha1.GPU, error)
	UpdateStatus(ctx context.Context, gPU *v1alpha1.GPU, opts v1.UpdateOptions) (*v1alpha1.GPU, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GPU, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GPUList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPU, err error)
	GPUExpansion
}

// gPUs implements GPUInterface
type gPUs struct {
	client rest.Interface
}

// newGPUs returns a GPUs
func newGPUs(c *ElasticgpuV1alpha1Client) *gPUs {
	return &gPUs{
		client: c.RESTClient(),
	}
}

// Get takes name of the gPU, and returns the corresponding gPU object, and an error if there is any.
func (c *gPUs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPU, err error) {
	result = &v1alpha1.GPU{}
	err = c.client.Get().
		Resource("gpus").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GPUs that match those selectors.
func (c *gPUs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPUList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GPUList{}
	err = c.client.Get().
		Resource("gpus").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gPUs.
func (c *gPUs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("gpus").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gPU and creates it.  Returns the server's representation of the gPU, and an error, if there is any.
func (c *gPUs) Create(ctx context.Context, gPU *v1alpha1.GPU, opts v1.CreateOptions) (result *v1alpha1.GPU, err error) {
	result = &v1alpha1.GPU{}
	err = c.client.Post().
		Resource("gpus").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPU).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gPU and updates it. Returns the server's representation of the gPU, and an error, if there is any.
func (c *gPUs) Update(ctx context.Context, gPU *v1alpha1.GPU, opts v1.UpdateOptions) (result *v1alpha1.GPU, err error) {
	result = &v1alpha1.GPU{}
	err = c.client.Put().
		Resource("gpus").
		Name(gPU.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPU).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *gPUs) UpdateStatus(ctx context.Context, gPU *v1alpha1.GPU, opts v1.UpdateOptions) (result *v1alpha1.GPU, err error) {
	result = &v1alpha1.GPU{}
	err = c.client.Put().
		Resource("gpus").
		Name(gPU.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPU).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gPU and deletes it. Returns an error if one occurs.
func (c *gPUs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("gpus").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gPUs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("gpus").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gPU.
func (c *gPUs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPU, err error) {
	result = &v1alpha1.GPU{}
	err = c.client.Patch(pt).
		Resource("gpus").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
