/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	elasticgpuiov1alpha1 "elasticgpu.io/elastic-gpu/api/elasticgpu.io/v1alpha1"
	versioned "elasticgpu.io/elastic-gpu/clientset/versioned"
	internalinterfaces "elasticgpu.io/elastic-gpu/informers/externalversions/internalinterfaces"
	v1alpha1 "elasticgpu.io/elastic-gpu/listers/elasticgpu.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ElasticGPUInformer provides access to a shared informer and lister for
// ElasticGPUs.
type ElasticGPUInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ElasticGPULister
}

type elasticGPUInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewElasticGPUInformer constructs a new informer for ElasticGPU type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewElasticGPUInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredElasticGPUInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredElasticGPUInformer constructs a new informer for ElasticGPU type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredElasticGPUInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticgpuV1alpha1().ElasticGPUs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticgpuV1alpha1().ElasticGPUs(namespace).Watch(context.TODO(), options)
			},
		},
		&elasticgpuiov1alpha1.ElasticGPU{},
		resyncPeriod,
		indexers,
	)
}

func (f *elasticGPUInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredElasticGPUInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *elasticGPUInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&elasticgpuiov1alpha1.ElasticGPU{}, f.defaultInformer)
}

func (f *elasticGPUInformer) Lister() v1alpha1.ElasticGPULister {
	return v1alpha1.NewElasticGPULister(f.Informer().GetIndexer())
}
