//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseGPUSource) DeepCopyInto(out *BaseGPUSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseGPUSource.
func (in *BaseGPUSource) DeepCopy() *BaseGPUSource {
	if in == nil {
		return nil
	}
	out := new(BaseGPUSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPU) DeepCopyInto(out *ElasticGPU) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPU.
func (in *ElasticGPU) DeepCopy() *ElasticGPU {
	if in == nil {
		return nil
	}
	out := new(ElasticGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticGPU) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUClaim) DeepCopyInto(out *ElasticGPUClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUClaim.
func (in *ElasticGPUClaim) DeepCopy() *ElasticGPUClaim {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticGPUClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUClaimList) DeepCopyInto(out *ElasticGPUClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticGPUClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUClaimList.
func (in *ElasticGPUClaimList) DeepCopy() *ElasticGPUClaimList {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticGPUClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUClaimSpec) DeepCopyInto(out *ElasticGPUClaimSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ElasticGPUClassName != nil {
		in, out := &in.ElasticGPUClassName, &out.ElasticGPUClassName
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUClaimSpec.
func (in *ElasticGPUClaimSpec) DeepCopy() *ElasticGPUClaimSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUClaimStatus) DeepCopyInto(out *ElasticGPUClaimStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUClaimStatus.
func (in *ElasticGPUClaimStatus) DeepCopy() *ElasticGPUClaimStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUClass) DeepCopyInto(out *ElasticGPUClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUClass.
func (in *ElasticGPUClass) DeepCopy() *ElasticGPUClass {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticGPUClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUClassList) DeepCopyInto(out *ElasticGPUClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticGPUClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUClassList.
func (in *ElasticGPUClassList) DeepCopy() *ElasticGPUClassList {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticGPUClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUList) DeepCopyInto(out *ElasticGPUList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticGPU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUList.
func (in *ElasticGPUList) DeepCopy() *ElasticGPUList {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticGPUList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUSource) DeepCopyInto(out *ElasticGPUSource) {
	*out = *in
	if in.QGPU != nil {
		in, out := &in.QGPU, &out.QGPU
		*out = new(QGPUElasticGPUSource)
		(*in).DeepCopyInto(*out)
	}
	if in.PhysicalGPU != nil {
		in, out := &in.PhysicalGPU, &out.PhysicalGPU
		*out = new(PhysicalGPUElasticGPUSource)
		(*in).DeepCopyInto(*out)
	}
	if in.GPUShare != nil {
		in, out := &in.GPUShare, &out.GPUShare
		*out = new(GPUShareElasticGPUSource)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUSource.
func (in *ElasticGPUSource) DeepCopy() *ElasticGPUSource {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUSpec) DeepCopyInto(out *ElasticGPUSpec) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.ElasticGPUSource.DeepCopyInto(&out.ElasticGPUSource)
	out.ClaimRef = in.ClaimRef
	in.NodeAffinity.DeepCopyInto(&out.NodeAffinity)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUSpec.
func (in *ElasticGPUSpec) DeepCopy() *ElasticGPUSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticGPUStatus) DeepCopyInto(out *ElasticGPUStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticGPUStatus.
func (in *ElasticGPUStatus) DeepCopy() *ElasticGPUStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticGPUStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeAffinity) DeepCopyInto(out *GPUNodeAffinity) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(v1.NodeSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeAffinity.
func (in *GPUNodeAffinity) DeepCopy() *GPUNodeAffinity {
	if in == nil {
		return nil
	}
	out := new(GPUNodeAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUShareElasticGPUSource) DeepCopyInto(out *GPUShareElasticGPUSource) {
	*out = *in
	out.BaseGPUSource = in.BaseGPUSource
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUShareElasticGPUSource.
func (in *GPUShareElasticGPUSource) DeepCopy() *GPUShareElasticGPUSource {
	if in == nil {
		return nil
	}
	out := new(GPUShareElasticGPUSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalGPUElasticGPUSource) DeepCopyInto(out *PhysicalGPUElasticGPUSource) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]BaseGPUSource, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalGPUElasticGPUSource.
func (in *PhysicalGPUElasticGPUSource) DeepCopy() *PhysicalGPUElasticGPUSource {
	if in == nil {
		return nil
	}
	out := new(PhysicalGPUElasticGPUSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QGPUElasticGPUSource) DeepCopyInto(out *QGPUElasticGPUSource) {
	*out = *in
	out.BaseGPUSource = in.BaseGPUSource
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QGPUElasticGPUSource.
func (in *QGPUElasticGPUSource) DeepCopy() *QGPUElasticGPUSource {
	if in == nil {
		return nil
	}
	out := new(QGPUElasticGPUSource)
	in.DeepCopyInto(out)
	return out
}
